name: "hello-action"
description: "teste go lang envorimnent"

inputs:
  greet: 
    description: 'Teste de inputs'
    required: true
    # default: 'World'

runs:
  using: composite
  steps:
  - run: go run main.go -t ${{ inputs.greet }}
    shell: bash
