name: "hello-action"
description: "teste go lang envorimnent"

inputs:
  who-to-greet: 
    description: 'Teste de inputs'
    required: true
    # default: 'World'

runs:
  using: composite
  steps:
  - run: echo $TEST_ENV && go run main.go
    shell: bash
